config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index]
        resources :posts, only: [] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      patch 'like', on: :member
      patch 'unlike', on: :member
    end
  end
  resources :comments, only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # Validation check
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  has_many :comments
  has_many :likes
  has_many :posts, foreign_key: 'author_id'

  def admin?
    role == 'admin' # Adjust based on how you determine if a user is an admin
  end

  def likes?(post)
    likes.exists?(post_id: post.id)
  end

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def recent_comments
    # criteria for recent comments, for example, comments within the last 7 days
    comments.where('created_at >= ?', 7.days.ago)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>All Users</h1>
<%= link_to "Sign out", destroy_user_session_path, 
        'data-turbo-method': :delete, class:"sign-out" %>
<ul>
  <% @users.each do |user| %>
    <div class="user-row">
      <div class="user-photo">
        <img src="<%= user.photo %>" alt="User Photo">
      </div>
      <div class="user-info">
        <%= link_to user.name, user_path(user) %>
        <div class="post-counter">Number of posts: <%= user.posts.count %></div>
      </div>
    </div>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Here is detail of a specific user</h1>
<%= link_to user_path(@user), class: "user-row-link" do %>
  <div class="user-row">
    <div class="user-photo">
    <img src="<%= @user.photo %>" alt="User Photo">
  </div>
    <div class="user-info">
      <h2><%= @user.name %></h2>
      <div class="post-counter">Number of posts: <%= @user.posts.count %></div>
    </div>
  </div>
<% end %>

<div class="bio-row">
  <h2>BIO</h2>
  <p><%= @user.bio %></p>
</div>

<% @user.most_recent_posts.each do |post| %>
  <%= link_to user_post_path(@user, post), class: "post-link" do %>
    <div class="post-row">
      <h3><%= post.title %></h3>
      <p><%= truncate(post.text, length: 50) %></p>
      <div class="post-stats">
        <span>Comments: <%= post.comments.count %></span>
        <span>Likes: <%= post.likes.count %></span>
        <%= link_to '<i class="fas fa-heart"></i>'.html_safe, user_post_path(@user, post, like: true), method: :post, class: 'like-link' %>

      </div>
    </div>
  <% end %>
<% end %>

<%= link_to 'See all posts', user_posts_path(@user), class: 'see-all-posts-btn' %>