config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: [:index]
        resources :posts, only: [] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      patch 'like', on: :member
      patch 'unlike', on: :member
    end
  end
  resources :comments, only: [:destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  # Validations check
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy # comments are destroyed when a post is destroyed
  has_many :likes, dependent: :destroy # likes are destroyed when a post is destroyed

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def liked_by?(user)
    likes.exists?(user:)
  end

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
# controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      before_action :set_user

      def index
        @posts = @user.posts.includes(:comments)
        render json: @posts
      end

      private

      def set_user
        @user = User.find(params[:user_id])
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource except: %i[like unlike]
  before_action :set_user
  before_action :set_post, only: %i[show edit update destroy]
  def index
    @posts = @user.posts.includes(:comments)
  end

  def show
    @comments = @post.comments
    @show ||= Comment.new(user: current_user, post: @post) # Initialize with the current post
  end

  def new
    @post = @user.posts.build
  end

  def create
    @post = @user.posts.build(post_params)
    @post.user_id = @user.id # Set the user_id explicitly
    if @post.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to user_post_path(current_user, @post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post

    if @post.destroy
      flash[:notice] = 'Post was successfully deleted.'
      redirect_to root_path
    else
      flash[:error] = 'Failed to delete the post.'
      redirect_to @post
    end
  end

  def like
    @post = Post.find(params[:id])
    @like = current_user.likes.find_or_initialize_by(post: @post)

    authorize! :create, Like # Authorize creation of Like objects

    if @like.save
      @like.update_likes_counter
      flash[:notice] = 'Liked the post!'
    else
      flash[:error] = 'Failed to like the post.'
    end

    redirect_to user_post_path(@user, @post)
  end

  def unlike
    @post = Post.find(params[:id])
    @like = current_user.likes.find_by(post: @post)

    authorize! :destroy, @like # Authorize destruction of Like objects

    if @like&.destroy
      @like.update_likes_counter
      flash[:notice] = 'Unliked the post!'
    else
      flash[:error] = 'Failed to unlike the post.'
    end

    redirect_to user_post_path(@user, @post)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = @user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def like_post_link(post, user)
    if post.liked_by?(user)
      link_to 'Likes', user_post_like_path(user, post), method: :delete, class: 'like-link'
    else
      link_to 'Like', user_post_like_path(user, post), method: :post, class: 'like-link'
    end
  end
end

app/views/posts/_form_partial.html.erb
<%= form_with(model: [@user, @post], local: true) do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <div class="actions">
    <%= form.submit 'Create Post' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1>Here is a list of posts for a given user</h1>
<%= link_to user_path(@user), class: "user-row-link" do %>
  <div class="user-photo">
    <img src="<%= @user.photo %>" alt="User Photo">
  </div>
  <div class="user-row">
    <div class="user-info">
      <h2><%= @user.name %></h2>
      <div class="post-counter">Number of posts: <%= @user.posts.count %></div>
    </div>
  </div>
<% end %>
<% recent_comments = [] %>
<% @user.posts.each do |post| %>
  <%= link_to user_post_path(@user, post), class: "post-link" do %>
    <div class="post-row">
      <h3><%= post.title %></h3>
      <p><%= truncate(post.text, length: 50) %></p>
      <div class="post-stats">
        <span>Comments: <%= post.comments.count %></span>
        <span>Likes: <%= post.likes.count %></span>
      </div>
    </div>
  <% end %>
  <% recent_comments.concat(post.most_recent_comments) %>
<% end %>

<div class="comments-container">
  <h2>Recent Comments</h2>
  <% recent_comments.each do |comment| %>
    <div class="comment">
      <span class="comment-author"><%= comment.user.name %>:</span>
      <span class="comment-text"><%= comment.text %></span>
    </div>
  <% end %>
</div>
<%= link_to 'Create a new post', new_user_post_path(@user), class: 'see-all-posts-btn' %>

app/views/posts/new.html.erb
<h1 class="new-post">Create a New Post</h1>

<%= form_for [@user, @post], url: user_posts_path(@user) do |f| %>
<div class="Add-post-container">

 <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

 <div class="field">
    <%= f.label :text %>
    <%= f.text_field :title %>
  </div>

  <div class="create-post">
    <%= f.submit 'Create Post', class:"create-post-btn" %>
  </div>
</div>
 
<% end %>

app/views/posts/show.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

<h1>Here is the detail of a post for a specific user</h1>
<div class="post-detail-row">
  <div class="post-title">
    <%= @post.title %>
  </div>
  <div class="post-content">
    <%= @post.text %>
  </div>

  <div class="post-stats">
    Comments: <%= @post.comments.count %> |
    Likes: <%= @post.likes.count %>
  </div>
  
  <!-- Delete post -->
<% if @post.user_id == current_user %>
  <%= button_to 'Delete', user_post_path(@user, @post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-button' %>
<% end %>

   <div class="like-form">
      <% if current_user.likes?(@post) %>
        <%= form_tag unlike_user_post_path(@user, @post), method: :patch, class: 'like-form' do %>
          <%= hidden_field_tag 'like', 'false' %>
          <%= submit_tag 'Unlike', class: 'unlike-link' %>
        <% end %>
      <% else %>
      <%= form_tag like_user_post_path(@user, @post), method: :patch, class: 'like-form' do %>
        <%= hidden_field_tag 'like', 'true' %>
        <%= submit_tag 'Like', class: 'like-link' %>
      <% end %>
    <% end %>
</div>

</div>

<!-- Add Comment Form -->
<div class="add-comments-container">
  <%= form_for [@user, @post, @new_comment || Comment.new] do |f| %>
    <div class="add-comment-div">
      <div class="comment">
        <%= f.label :text %>
        <%= f.text_area :text %>
      </div>
      <div class="add-comment-button">
        <%= f.submit "Add Comment" %>
      </div>
    </div>
  <% end %>
</div>

<!-- Display Existing Comments -->
<div class="comments-container">
  <h2>Comments</h2>
  <% @comments.each do |comment| %>
    <div class="comment">
      <span class="comment-author"><%= comment.user.name %> :</span>
      <span class="comment-text"><%= comment.text %></span>
      <!-- Delete comment -->
      <% if can? :destroy, comment %>
        <%= button_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-button' %>
      <% end %>
    </div>
  <% end %>

<% unless @new_comment.nil? || @new_comment.new_record? %>
  <!-- Display New Comment -->
  <div class="comment">
    <span class="comment-author"><%= @new_comment.user.name %> :</span>
    <span class="comment-text"><%= @new_comment.text %></span>
    <!-- Delete comment -->
    <% if can? :destroy, @new_comment %>
      <%= button_to 'Delete', [@user, @post, @new_comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-button' %>
    <% end %>
  </div>
<% end %>


</div>